### ISSUE TITLE
May you please draft a new release

### ISSUE THREAD

**Issue by fiete201** [libcdio/libcdio-paranoia#41]
Hi,
first of all, thanks for your work!
May you please create a new release so that the most recent changes are made available through the distributions.
For me especially https://github.com/rocky/libcdio-paranoia/pull/38 is interesting since I can't rip CDs at all without this fix.

Thanks! Fiete

**Comment by rocky** [comment]
Right now I am at BlackHat Asia 2024 and I will be vacationing in Malaysia after that.  So I can't contemplate a release right now. However after I get to the U.S. I do plan on releasing soon (along with a number of other backlogged open-source things.)

**Comment by ryandesign** [comment]
Version 10.2+2.0.2 was released in May 2024 so this issue could be closed.
