### ISSUE TITLE
undefined TESTING_IS_FINISHED exported to downstream projects

### ISSUE THREAD

**Issue by Dudemanguy** [libcdio/libcdio-paranoia#48]
So within the public header `cdda.h`, there is a `TESTING_IS_FINISHED` which is not defined and triggers a `Wundef` warning in any downstream project. That's a bit unfortunate when trying to build with `Werror` so we have to work around it. 

This is the offending section:
https://github.com/libcdio/libcdio-paranoia/blob/e1cee5696896ef466d9d25a56684973b0397774a/include/cdio/paranoia/cdda.h#L180-L186

I'm not 100% sure is this ever even used? Nothing seems to set `TESTING_IS_FINISHED` during configure and I don't see any obvious build options that would do that so it seems to me that this entire section is totally obsolete and can just be removed. If it is needed, maybe it could be moved to some other internal header instead? Library users shouldn't ever need this at any rate.

**Comment by rocky** [comment]
I've removed this code in commit bd9481d.  Thanks for reporting the problem.

For the record, this is code from the very first commit in splitting this off from Xiph's cdparanoia. In cdparanoia, there were other error failure-mode models that you could use the cdparanoia binary to use. These were never supported in this code, and clearly, the demand for these, both here and in cdparanoia, is nonexistent. 

So at this point, we may as well remove this.
